import type { Batiment, Entreprise, Marche, Identifiant, Pole, Utilisateur } from './types';

export const SEED_UTILISATEURS: Utilisateur[] = [
  { id: 1, nom: 'FEUILLAS', prenom: 'Jordy', nomComplet: 'FEUILLAS Jordy', email: 'j.feuillas@ghu-paris.fr' },
  { id: 2, nom: 'SAID', prenom: 'Ahmed', nomComplet: 'SAID Ahmed', email: 'ahmed.said@ghu-paris.fr' },
  { id: 3, nom: 'GRISON', prenom: 'Jérémy', nomComplet: 'GRISON Jérémy', email: 'jeremy.grison@ghu-paris.fr' },
  { id: 4, nom: 'BALLESTER', prenom: 'Luis', nomComplet: 'BALLESTER Luis', email: 'l.ballester@ghu-paris.fr' },
  { id: 5, nom: 'NESIGBA', prenom: 'Alpha', nomComplet: 'NESIGBA Alpha', email: 'a.nesigba@ghu-paris.fr' },
  { id: 6, nom: 'SIRI', prenom: 'Thierry', nomComplet: 'SIRI Thierry', email: 't.siri@ghu-paris.fr' },
  { id: 7, nom: 'GUILLAUME', prenom: 'Marc', nomComplet: 'GUILLAUME Marc', email: 'marc.guillaume@ghu-paris.fr' },
  { id: 8, nom: 'CLERGET', prenom: 'Baudouin', nomComplet: 'CLERGET Baudouin', email: 'b.clerget@ghu-paris.fr' },
  { id: 9, nom: 'TOUATI', prenom: 'Madhi', nomComplet: 'TOUATI Madhi', email: 'm.touati@ghu-paris.fr' },
  { id: 10, nom: 'VITTORI', prenom: 'Anthony', nomComplet: 'VITTORI Anthony', email: 'a.vittori@ghu-paris.fr' },
  { id: 11, nom: 'VITTORI', prenom: 'Alexis', nomComplet: 'VITTORI Alexis', email: 'alexis.vittori@ghu-paris.fr' },
  { id: 12, nom: 'DA SILVA', prenom: 'Georges', nomComplet: 'DA SILVA Georges', email: 'g.dasilva@ghu-paris.fr' },
  { id: 13, nom: 'KIALA', prenom: 'Ralph', nomComplet: 'KIALA Ralph', email: 'r.kiala@ghu-paris.fr' },
  { id: 14, nom: 'HORVAT', prenom: 'Adolphe', nomComplet: 'HORVAT Adolphe', email: 'a.horvat@ghu-paris.fr' },
  { id: 15, nom: 'PLANO', prenom: 'Richard', nomComplet: 'PLANO Richard', email: 'r.plano@ghu-paris.fr' },
  { id: 16, nom: 'LETOURNEUR', prenom: 'Olivier', nomComplet: 'LETOURNEUR Olivier', email: 'o.letourneur@ghu-paris.fr' },
  { id: 17, nom: 'LE DEVEHAT', prenom: 'Yannick', nomComplet: 'LE DEVEHAT Yannick', email: 'y.le_devehat@ghu-paris.fr' },
  { id: 18, nom: 'LAHOUAZI', prenom: 'Belkacem', nomComplet: 'LAHOUAZI Belkacem', email: 'b.lahouazi@ghu-paris.fr' },
  { id: 19, nom: 'SAINT MARTIN', prenom: 'Eddy', nomComplet: 'SAINT MARTIN Eddy', email: 'e.saint_martin@ghu-paris.fr' },
  { id: 20, nom: 'PUGIN', prenom: 'Hervé', nomComplet: 'PUGIN Hervé', email: 'h.pugin@ghu-paris.fr' },
  { id: 21, nom: 'THEZENAS', prenom: 'Mehdy', nomComplet: 'THEZENAS Mehdy', email: 'm.thezenas@ghu-paris.fr' },
  { id: 22, nom: 'GUICHARD', prenom: 'Pierre', nomComplet: 'GUICHARD Pierre', email: 'p.guichard@ghu-paris.fr' },
  { id: 23, nom: 'TRAORE', prenom: 'KABA', nomComplet: 'TRAORE KABA', email: 'kaba-adama.traore@ghu-paris.fr' },
  { id: 24, nom: 'ATLAN', prenom: 'DAVID', nomComplet: 'ATLAN DAVID', email: 'david.atlan@ghu-paris.fr' },
  { id: 25, nom: 'GARNIER', prenom: 'Philippe', nomComplet: 'GARNIER Philippe', email: 'p.garnier@ghu-paris.fr' },
  { id: 26, nom: 'BERTOLINO', prenom: 'Sarah', nomComplet: 'BERTOLINO Sarah', email: 'sarah.bertolino@ghu-paris.fr' },
  { id: 27, nom: 'HADJAM', prenom: 'Kaoutar', nomComplet: 'HADJAM Kaoutar', email: 'khaoutar.hadjam@ghu-paris.fr' },
  { id: 28, nom: 'DOUIRI', prenom: 'Hinda', nomComplet: 'DOUIRI Hinda', email: 'henda.douiri@ghu-paris.fr' },
  { id: 29, nom: 'BONNEFOI', prenom: 'Alain', nomComplet: 'BONNEFOI Alain', email: 'bonnefoi@ghu-paris.fr' },
];

export const SEED_BATIMENTS: Batiment[] = [
  { id: 1, numero: '001', nom: 'BAT 1 (LOCAUX VIDES)', tva_defaut: '20' },
  { id: 2, numero: '002', nom: 'BAT 2 ACCUEIL - STANDARD', tva_defaut: '20' },
  { id: 3, numero: '003', nom: 'BAT 3 LOGEMENT GARAGE', tva_defaut: '20' },
  { id: 4, numero: '004', nom: 'BAT 4 PAVILLON DIRECTEUR', tva_defaut: '20' },
  { id: 5, numero: '005', nom: 'BAT 5 IFSI (ECOLE VIRGINIE OLIVIER)', tva_defaut: '20' },
  { id: 6, numero: '006', nom: 'BAT 6 F.H.F', tva_defaut: '20' },
  { id: 7, numero: '007', nom: 'BAT 7 ARC EN CIEL', tva_defaut: '20' },
  { id: 8, numero: '008', nom: 'BAT 8 CPOA', tva_defaut: '20' },
  { id: 9, numero: '010', nom: 'BAT 010 FONDATION ST ANNE', tva_defaut: '20' },
  { id: 10, numero: '012', nom: 'BAT 12 MAGNAN S.15', tva_defaut: '20' },
  { id: 11, numero: '015', nom: 'BAT N°15 BAT JARDIN', tva_defaut: '20' },
  { id: 12, numero: '018', nom: 'BAT 18 PIERA AULAGNIER FERRUS./JOFF. S.13', tva_defaut: '20' },
  { id: 13, numero: '019', nom: 'BAT 19 IPNP - CRC', tva_defaut: '20' },
  { id: 14, numero: '020', nom: 'BAT 20 B.BALL', tva_defaut: '20' },
  { id: 15, numero: '021', nom: 'Bâtiment 21 INSERM', tva_defaut: '20' },
  { id: 16, numero: '022', nom: 'BAT 22 EEG SAVS (service Transféré au BAT24)', tva_defaut: '20' },
  { id: 17, numero: '023', nom: 'BAT 23 EEG', tva_defaut: '20' },
  { id: 18, numero: '024', nom: 'BAT 24 EEG SAVS', tva_defaut: '20' },
  { id: 19, numero: '025', nom: 'BAT 25 DIM', tva_defaut: '20' },
  { id: 20, numero: '026', nom: 'BAT 26 R.GARCIN', tva_defaut: '20' },
  { id: 21, numero: '027', nom: 'Batiment INSERM', tva_defaut: '20' },
  { id: 22, numero: '028', nom: 'BAT 28 MUTUELLES', tva_defaut: '20' },
  { id: 23, numero: '029', nom: 'BAT 29 REPROGRAPHIE', tva_defaut: '20' },
  { id: 24, numero: '031', nom: 'BAT 31 PIERRE JANET', tva_defaut: '20' },
  { id: 25, numero: '032', nom: 'BAT 32 FUIDES MEDICAUX', tva_defaut: '20' },
  { id: 26, numero: '035', nom: 'BAT 35 RESTAURANT PERSONNEL', tva_defaut: '20' },
  { id: 27, numero: '036', nom: 'BAT 36 CHATEAU D\'EAU (ROTONDE)', tva_defaut: '20' },
  { id: 28, numero: '037', nom: 'BAT 37 PC SECURITE', tva_defaut: '20' },
  { id: 29, numero: '038', nom: 'BAT 38 LOCAL COMPACTAGE', tva_defaut: '20' },
  { id: 30, numero: '039', nom: 'BAT 39 UCP', tva_defaut: '20' },
  { id: 31, numero: '040', nom: 'BAT 40 LABORATOIRE DE NEUROPATHOLOGIE', tva_defaut: '20' },
  { id: 32, numero: '041', nom: 'BATIMENT 41 SHU SECTEUR 14', tva_defaut: '20' },
  { id: 33, numero: '042', nom: 'BAT 42 LOCAL SYNDICAL', tva_defaut: '20' },
  { id: 34, numero: '043', nom: 'BAT 43 LABORATOIRE DE BIOLOGIE', tva_defaut: '20' },
  { id: 35, numero: '044', nom: 'BAT 44 INFIRMERIE PREFECTURE POLICE', tva_defaut: '20' },
  { id: 36, numero: '045', nom: 'BAT 045', tva_defaut: '20' },
  { id: 37, numero: '046', nom: 'BAT 46 PREFABRIQUE SERVICE PERSONNEL', tva_defaut: '20' },
  { id: 38, numero: '047', nom: 'BAT 47 DIRECTION GENERALE', tva_defaut: '20' },
  { id: 39, numero: '049', nom: 'BAT 49 PREFABRIQUE ADMISSION', tva_defaut: '20' },
  { id: 40, numero: '050', nom: 'BAT 50 PAV. A', tva_defaut: '20' },
  { id: 41, numero: '051', nom: 'BAT 51 PAV. B', tva_defaut: '20' },
  { id: 42, numero: '052', nom: 'BAT 52 PAV. C', tva_defaut: '20' },
  { id: 43, numero: '053', nom: 'BAT 53 PAV. D', tva_defaut: '20' },
  { id: 44, numero: '054', nom: 'BAT 54 SECTEUR 17 PAV E', tva_defaut: '20' },
  { id: 45, numero: '055', nom: 'BAT 55 PAV F S.17', tva_defaut: '20' },
  { id: 46, numero: '056', nom: 'BAT 56 CHAPELLE/ SALLE DE COURS', tva_defaut: '20' },
  { id: 47, numero: '057', nom: 'BAT 57 LICERE', tva_defaut: '20' },
  { id: 48, numero: '058', nom: 'BAT 58 DIRECTION INGENERIE DES TRAVAUX, DE LA MAINTENANCE & DU PATRIMOINE', tva_defaut: '20' },
  { id: 49, numero: '059', nom: 'BAT 59 PAV G ASSOCIATIONS', tva_defaut: '20' },
  { id: 50, numero: '060', nom: 'BAT 60 INFANTO-JUVENILE PAV H', tva_defaut: '20' },
  { id: 51, numero: '061', nom: 'BAT 61 PAV I INTERSECTEUR 6 GUIDANCE INFANTILE', tva_defaut: '20' },
  { id: 52, numero: '062', nom: 'BAT 62 SECTEUR 16 PAV. J', tva_defaut: '20' },
  { id: 53, numero: '063', nom: 'BAT 63 PAV K SECTEUR 16', tva_defaut: '20' },
  { id: 54, numero: '064', nom: 'BAT 64 BAT L', tva_defaut: '20' },
  { id: 55, numero: '065', nom: 'BAT 65 INFORMATIQUE', tva_defaut: '20' },
  { id: 56, numero: '066', nom: 'BAT 66 COMMUNICATION', tva_defaut: '20' },
  { id: 57, numero: '067', nom: 'BAT 67 PAVILLON DE L\'HORLOGE', tva_defaut: '20' },
  { id: 58, numero: '068', nom: 'BAT 68 ATELIERS TECHNIQUES & SALLE DE GARDE', tva_defaut: '20' },
  { id: 59, numero: '070', nom: 'BAT 70 CRECHE 5 TER ALESIA', tva_defaut: '20' },
  { id: 60, numero: '071', nom: 'BAT 71 IRM 3T', tva_defaut: '20' },
  { id: 61, numero: '072', nom: 'BAT 72 RELAIS H CENTRE DE VIE', tva_defaut: '20' },
  { id: 62, numero: '073', nom: 'LOCAUX DASRI/DAOM', tva_defaut: '20' },
  { id: 63, numero: '075', nom: 'BAT 75 CABINE HTBT ALESIA', tva_defaut: '20' },
  { id: 64, numero: '077', nom: 'BAT 77 PAVILLON RUE BROUSSAIS-CABANIS', tva_defaut: '20' },
  { id: 65, numero: '079', nom: 'HANGAR TRANSPORT LOGISTIQUE', tva_defaut: '20' },
  { id: 66, numero: '081', nom: 'BAT 81 COUR PAV K', tva_defaut: '20' },
  { id: 67, numero: '082', nom: 'BAT 82 COUR PAV B', tva_defaut: '20' },
  { id: 68, numero: '083', nom: 'BAT 83 COUR PAV C', tva_defaut: '20' },
  { id: 69, numero: '084', nom: 'BAT 84 COUR PAV D', tva_defaut: '20' },
  { id: 70, numero: '085', nom: 'BAT 85 COUR PAV E', tva_defaut: '20' },
  { id: 71, numero: '086', nom: 'BAT 86 COUR PAV H', tva_defaut: '20' },
  { id: 72, numero: '087', nom: 'BAT 87 COUR PAV I', tva_defaut: '20' },
  { id: 73, numero: '088', nom: 'BAT 88 COUR PAV J', tva_defaut: '20' },
  { id: 74, numero: '089', nom: 'INSTITUT DE PSYCHANALYSE', tva_defaut: '20' },
  { id: 75, numero: '090', nom: 'BAT 90 BUREAUX SECTEUR 17 E& F', tva_defaut: '20' },
  { id: 76, numero: '091', nom: 'BAT 91 PAV F OFFICE BUREAU CADRE', tva_defaut: '20' },
  { id: 77, numero: '092', nom: 'BAT 092 rdc Atelier Thérapeutique', tva_defaut: '20' },
  { id: 78, numero: '093', nom: 'BAT 93 ECOLE INFANTO JUVENILE', tva_defaut: '20' },
  { id: 79, numero: '094', nom: 'BAT 94 BUREAU PAV K&J 16', tva_defaut: '20' },
  { id: 80, numero: '098', nom: 'BAT 98 IRM 3T Recherche', tva_defaut: '20' },
  { id: 81, numero: '100', nom: 'CMME S3 LEVY VALENSI', tva_defaut: '20' },
  { id: 82, numero: '101', nom: 'MODULAIRE UNITE DE SOINS SOMATIQUES - CONSULTATIONS SMES', tva_defaut: '20' },
  { id: 83, numero: '102', nom: 'MODULAIRE CONSULTATIONS NEUROSCIENCES', tva_defaut: '20' },
  { id: 84, numero: '105', nom: 'NEUROSCIENCES', tva_defaut: '20' },
  { id: 85, numero: '200', nom: 'RIDDER Hopital de jour(déménagement du 4 étage IPP (07/2014)', tva_defaut: '20' },
  { id: 86, numero: '201', nom: 'GARANCIERE - 17 Rue GARANCIERE Centre d\'accueil de crise', tva_defaut: '20' },
  { id: 87, numero: '203', nom: 'CAILLAUX - 8bis rue CAILLAUX foyer post-cure', tva_defaut: '20' },
  { id: 88, numero: '205', nom: 'ALESIA - 145 Rue ALESIA cmp/cattp', tva_defaut: '20' },
  { id: 89, numero: '208', nom: 'VITRY 1 - Appt 99 rue Charles Infroit', tva_defaut: '20' },
  { id: 90, numero: '213', nom: 'SAINT DIDIER - 29 rue Saint Didier CMP & CATTP', tva_defaut: '20' },
  { id: 91, numero: '215', nom: 'SMPR - Prison de la Santé', tva_defaut: '20' },
  { id: 92, numero: '217', nom: 'VITRY 2 - Appt Camille Blanc', tva_defaut: '20' },
  { id: 93, numero: '218', nom: 'CIAPA / GOBELINS - 7 Rue des Gobelins foyer post-cure', tva_defaut: '20' },
  { id: 94, numero: '219', nom: 'FOSSES St JACQUES - 24 Rue des Fossés St Jacques', tva_defaut: '20' },
  { id: 95, numero: '220', nom: 'LAMARTINE cmp', tva_defaut: '20' },
  { id: 96, numero: '221', nom: 'PICOT - 6 rue Picot Hopital de Jour', tva_defaut: '20' },
  { id: 97, numero: '223', nom: 'NIOX - 11 Rue colonel Niox cmp & cattp', tva_defaut: '20' },
  { id: 98, numero: '224', nom: 'TUTELLES 26, rue Bénard 75014', tva_defaut: '20' },
  { id: 99, numero: '225', nom: 'FALGUIERE - 14 Cites Falguière', tva_defaut: '20' },
  { id: 100, numero: '226', nom: 'POISSONNIERE - Appartement Relais', tva_defaut: '20' },
  { id: 101, numero: '227', nom: 'IPB- 26 bd Brune 75014 Paris', tva_defaut: '20' },
  { id: 102, numero: '228', nom: 'MILLON 3-5 rue Eugène MILLON Paris 15', tva_defaut: '20' },
  { id: 103, numero: '229', nom: 'VARENNE', tva_defaut: '20' },
  { id: 104, numero: '232', nom: 'SEBASTOPOL - SMIRNOFF', tva_defaut: '20' },
  { id: 105, numero: '236', nom: 'La Grande Porte', tva_defaut: '20' },
  { id: 106, numero: '237', nom: 'Ferrus DRH', tva_defaut: '20' },
  { id: 107, numero: '315', nom: 'GROUPE ELECTROGENE ZONE OUEST 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 108, numero: '316', nom: 'POSTE DE TRANFO ELEC OUEST 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 109, numero: '328', nom: 'ANCIENNE SALLE AUTOCOMMUTATEUR 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 110, numero: '331', nom: 'STATION DE RELEVAGE 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 111, numero: '332', nom: 'STOCKAGE PRODUITS INFLAMMABLES 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 112, numero: '333', nom: 'LOCAL OXYGENE LA ROSERAIE 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 113, numero: '340', nom: 'USLD LA ROSERAIE BATIMENT CENTRAL 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 114, numero: '341', nom: 'USLD LA ROSERAIE PAVILLON RENOIR 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 115, numero: '342', nom: 'LA ROSERAIE PAVILLON MONET 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 116, numero: '343', nom: 'LA ROSERAIE PAVILLON DEGAS 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 117, numero: '358', nom: 'BATIMENT 358 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 118, numero: '359', nom: 'ANNEXE PHARMACIE 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 119, numero: '363', nom: 'AFT ENFANT 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 120, numero: '367', nom: 'US 67 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 121, numero: '368', nom: 'US 68 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 122, numero: '369', nom: 'PSP 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 123, numero: '375', nom: 'CHAUFFERIE IFITS 93330 Neuilly Sur Marne', tva_defaut: '20' },
  { id: 124, numero: '388', nom: 'ARCHIVES + CRECHE FARANDOLE + LOGEMNT 93330 Neuilly Sur Marn', tva_defaut: '20' },
  { id: 125, numero: '402', nom: 'TOURELLES 14, rue des Tourelles 75020 Paris', tva_defaut: '20' },
  { id: 126, numero: '403', nom: 'CARDEURS 15 square des Cardeurs 75020 Paris', tva_defaut: '20' },
  { id: 127, numero: '407', nom: 'ST GERVAIS HUBERT MIGNOT 12 Rue Hospitalieres St Gervais 75', tva_defaut: '20' },
  { id: 128, numero: '408', nom: 'TOUR D\'AUVERGNE 18-20 Rue de la Tour d\'Auvergne 75009 Paris', tva_defaut: '20' },
  { id: 129, numero: '416', nom: 'MARCADET CARPEAUX 258 Rue Marcadet, 75018 Paris', tva_defaut: '20' },
  { id: 130, numero: '418', nom: 'MARCADET LA TERRASSE 222 bis, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 131, numero: '419', nom: 'ORDENER 40, rue Ordener 75018 Paris', tva_defaut: '20' },
  { id: 132, numero: '420', nom: 'CHAPELLE 28, rue de la Chapelle 75018 Paris', tva_defaut: '20' },
  { id: 133, numero: '421', nom: 'CHARLES LAUTH 4, rue Charles Lauth 75018 Paris', tva_defaut: '20' },
  { id: 134, numero: '423', nom: 'CRIMEE 99, rue de Crimée 75019 Paris', tva_defaut: '20' },
  { id: 135, numero: '424', nom: 'GOUBET 26, rue Goubet 75019 Paris', tva_defaut: '20' },
  { id: 136, numero: '425', nom: 'SOLIDARITE CLUB SOLO 10-12 rue de la Solidarité 75019 Paris', tva_defaut: '20' },
  { id: 137, numero: '428', nom: 'PASTEUR 11 Rue Pasteur 75011 Paris', tva_defaut: '20' },
  { id: 138, numero: '429', nom: 'TELEGRAPHE 9-11, rue du Télégraphe 75020 Paris', tva_defaut: '20' },
  { id: 139, numero: '430', nom: 'REBEVAL 45 Rue Rebeval, 75019 Paris', tva_defaut: '20' },
  { id: 140, numero: '433', nom: 'CLAUZEL 5, rue Clauzel 75009 Paris', tva_defaut: '20' },
  { id: 141, numero: '436', nom: 'VILLETTE 36-42, rue de la Villette 75019 Paris', tva_defaut: '20' },
  { id: 142, numero: '438', nom: 'METAIRIE 5, cour de la Métairie 75020 Paris', tva_defaut: '20' },
  { id: 143, numero: '440', nom: 'Batiment 440 Belleville', tva_defaut: '20' },
  { id: 144, numero: '450', nom: 'MARCADET LA METHADONE 224, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 145, numero: '451', nom: 'MARCADET LABO ET IPA 258 rue Marcadet Bâtiment N 75018 Paris', tva_defaut: '20' },
  { id: 146, numero: '452', nom: 'JEMMAPES 120, quai de Jemmapes 75010 Paris', tva_defaut: '20' },
  { id: 147, numero: '453', nom: 'MEAUX 64 ter, rue de Meaux 75019 Paris', tva_defaut: '20' },
  { id: 148, numero: '454', nom: 'BUISSON ST LOUIS D. GREY 7-13, rue du Buisson Saint-Louis 75', tva_defaut: '20' },
  { id: 149, numero: '455', nom: 'REMY DE GOURMONT 18, rue Rémy de Gourmont - 75019 Paris', tva_defaut: '20' },
  { id: 150, numero: '456', nom: 'PIERRE BAYLE 6-10, rue Pierre Bayle 75020 Paris', tva_defaut: '20' },
  { id: 151, numero: '459', nom: 'MARCADET BUREAU MEDECIN 220 bis, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 152, numero: '460', nom: 'MARCADET BUREAU CADRE DE SANTE 222 bis, rue Marcadet 75018', tva_defaut: '20' },
  { id: 153, numero: '461', nom: 'ABBEVILLE 11, rue d\'Abbeville 75010 Paris', tva_defaut: '20' },
  { id: 154, numero: '462', nom: 'SAINT VICTOR 7 rue Saint-Victor, 93100 Montreuil', tva_defaut: '20' },
  { id: 155, numero: '463', nom: 'LESPAGNOL R+0 3, rue Lespagnol - 75020 Paris', tva_defaut: '20' },
  { id: 156, numero: '464', nom: 'MARCADET LA TERRASSE (ANNEXE) 224, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 157, numero: '466', nom: 'AVRON 129 Rue d\'Avron, 75020 Paris', tva_defaut: '20' },
  { id: 158, numero: '467', nom: 'HAUTEVILLE 24-26, rue d\'Hauteville 75010 Paris', tva_defaut: '20' },
  { id: 159, numero: '468', nom: 'THIONVILLE 14, rue de Thionville 75019 Paris', tva_defaut: '20' },
  { id: 160, numero: '469', nom: 'VIGNOLES 93 rue Vignoles, 75020 Paris', tva_defaut: '20' },
  { id: 161, numero: '471', nom: 'MARCADET SALLE DE REUNION 220, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 162, numero: '474', nom: 'CLIGNANCOURT 147 Rue de Clignancourt, 75018 Paris', tva_defaut: '20' },
  { id: 163, numero: '475', nom: 'AVRON ANTENNE ADMINISTRATIVE 129 Rue d\'Avron, 75020 Paris', tva_defaut: '20' },
  { id: 164, numero: '477', nom: 'NAVARIN 29 Rue de Navarin, 75009 Paris', tva_defaut: '20' },
  { id: 165, numero: '478', nom: 'LEON GIRAUD 5 Rue Léon Giraud, 75019 Paris', tva_defaut: '20' },
  { id: 166, numero: '479', nom: 'PARADIS 32, rue de Paradis 75010 Paris', tva_defaut: '20' },
  { id: 167, numero: '480', nom: 'SAMPAIX 21-23, rue Lucien Sampaix 75010 Paris', tva_defaut: '20' },
  { id: 168, numero: '483', nom: 'FLANDRE 114, avenue de Flandre 75019 Paris', tva_defaut: '20' },
  { id: 169, numero: '484', nom: 'BICHAT BATIMENT 12 SI 4, avenue de la Porte de Saint-Ouen 75', tva_defaut: '20' },
  { id: 170, numero: '485', nom: 'BICHAT 4, avenue de la Porte de Saint-Ouen 75018 Paris', tva_defaut: '20' },
  { id: 171, numero: '486', nom: 'DARIUS MILHAUD 32 Allée Darius Milhaud, 75019 Paris', tva_defaut: '20' },
  { id: 172, numero: '487', nom: 'DARIUS MILHAUD 38 Allée Darius Milhaud, 75019 Paris', tva_defaut: '20' },
  { id: 173, numero: '489', nom: 'LASALLE 10-14, rue du Général Lasalle 75019 Paris', tva_defaut: '20' },
  { id: 174, numero: '495', nom: 'DEBIDOUR 4 Avenue Debidour, 75019, Paris', tva_defaut: '20' },
  { id: 175, numero: '496', nom: 'LAONNAIS 4 square du Laonnais, 75019 Paris', tva_defaut: '20' },
  { id: 176, numero: '514', nom: 'DOLLFUS 8 Rue Jean Dollfus, 75018 Paris', tva_defaut: '20' },
  { id: 177, numero: '519', nom: 'MARCADET ELP 218, rue Marcadet 75018 Paris', tva_defaut: '20' },
  { id: 178, numero: '522', nom: 'LESPAGNOL R+1 5, rue Lespagnol - 75020 Paris', tva_defaut: '20' },
  { id: 179, numero: '531', nom: 'CHOMEL 12, rue Chomel 75007 Paris', tva_defaut: '20' },
  { id: 180, numero: '532', nom: 'GRENELLE 164, rue de Grenelle 75007 Paris', tva_defaut: '20' },
  { id: 181, numero: '533', nom: 'BUCAREST 7, rue Bucarest 75008 Paris', tva_defaut: '20' },
  { id: 182, numero: '534', nom: 'LISBONNE 3 rue de Lisbonne, 75008 Paris', tva_defaut: '20' },
  { id: 183, numero: '535', nom: 'COMPOINT 20, villa Compoint 75017 Paris', tva_defaut: '20' },
  { id: 184, numero: '536', nom: 'LEBOUTEUX 5, rue Lebouteux 75017 Paris', tva_defaut: '20' },
  { id: 185, numero: '537', nom: 'LEMERCIER 110, rue Lemercier 75017 PARIS', tva_defaut: '20' },
  { id: 186, numero: '538', nom: 'ARMAILLE MARMOTTAN 17-19 rue d\'Armaillé, 75017 Paris', tva_defaut: '20' },
  { id: 187, numero: '539', nom: 'PIERRE DEMOURS 15, rue Pierre Demours 75017 Paris', tva_defaut: '20' },
  { id: 188, numero: '540', nom: 'POUCHET 28 rue Pouchet - 75017 Paris', tva_defaut: '20' },
  { id: 189, numero: '541', nom: 'ROCHEFORT 31-33 rue Henri Rochefort 75017 Paris', tva_defaut: '20' },
  { id: 190, numero: '542', nom: 'SALNEUVE 18 rue Salneuve 75017 Paris', tva_defaut: '20' },
  { id: 191, numero: '543', nom: 'SIMPLON 56 Rue du Simplon, 75018 Paris', tva_defaut: '20' },
  { id: 192, numero: '544', nom: 'OBERKAMPF 140 RUE Oberkampf 75011 Paris', tva_defaut: '20' },
  { id: 193, numero: '545', nom: 'LEVERT 27 rue Levert 75020 Paris', tva_defaut: '20' },
  { id: 194, numero: '549', nom: '152, boulevard McDonald, 75019 Paris', tva_defaut: '20' },
  { id: 195, numero: '612', nom: 'HORTICOLE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 196, numero: '613', nom: 'MOULIN 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 197, numero: '619', nom: 'CENTRALE THERMIQUE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 198, numero: '621', nom: 'CHÂTEAU D\'EAU 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 199, numero: '624', nom: 'PICARDIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 200, numero: '625', nom: 'STANDARD 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 201, numero: '626', nom: 'LOGE BALLAINVILLIERS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 202, numero: '627', nom: 'SALLE POLYVALENTE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 203, numero: '630', nom: 'HUREPOIX 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 204, numero: '631', nom: 'CHAPELLE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 205, numero: '632', nom: 'NORMANDIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 206, numero: '633', nom: 'MAINE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 207, numero: '634', nom: 'LORRAINE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 208, numero: '640', nom: 'SERVICE GENERAUX 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 209, numero: '641', nom: 'VALOIS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 210, numero: '643', nom: 'ROUSSILLON 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 211, numero: '644', nom: 'SAVOIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 212, numero: '645', nom: 'TOURRAINE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 213, numero: '650', nom: 'LINGERIE / BUANDERIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 214, numero: '651', nom: 'SERVICE ADMINISTRATIFS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 215, numero: '652', nom: 'SERVICE TECHNIQUES 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 216, numero: '653', nom: 'PHARMACIE / LABORATOIRE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 217, numero: '654', nom: 'BOURNEVILLE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 218, numero: '655', nom: 'DIANE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 219, numero: '656', nom: 'FLORE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 220, numero: '657', nom: 'CALYPSO 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 221, numero: '658', nom: 'ESOPE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 222, numero: '660', nom: 'GALATEE (SOINS PROLONGES) 91360 EPINAY SUR ORGE', tva_defaut: '20' },
  { id: 223, numero: '661', nom: 'ARIANE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 224, numero: '662', nom: 'POSTE DE TRANSFORMATION VENDEMIAIRE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 225, numero: '663', nom: 'POSTE PLATEAU 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 226, numero: '664', nom: 'POSTE HT MAINE LORRAINE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 227, numero: '665', nom: 'LOCAL GE (SECOURS) 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 228, numero: '667', nom: 'PHARMACIE LABORATOIRE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 229, numero: '668', nom: 'POSTE HT BUANDERIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 230, numero: '669', nom: 'POSTE DE LIVRAISON EDF ASILE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 231, numero: '671', nom: 'POSTE HT CRECHE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 232, numero: '672', nom: 'CUISINE & MAGASINS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 233, numero: '673', nom: 'CEDRES 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 234, numero: '674', nom: 'MARONNIERS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 235, numero: '675', nom: 'TILLEULS 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 236, numero: '676', nom: 'GLYCINES (FOYER ETUDIANT) 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 237, numero: '677', nom: 'IFSI 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 238, numero: '679', nom: 'CHARMES 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 239, numero: '680', nom: 'LOGE DE LA VALLEE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 240, numero: '681', nom: 'POSTE HT COLONIE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 241, numero: '682', nom: 'POSTE HT BOURNEVILLE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 242, numero: '683', nom: 'POSTE HT SERRE 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 243, numero: '686', nom: 'MAS (LA GILQUINIERE) 91360 Epinay Sur Orge', tva_defaut: '20' },
  { id: 244, numero: '700', nom: 'HENRI EY 15 avenue de la Porte de Choisy 75013 Paris', tva_defaut: '20' },
  { id: 245, numero: '701', nom: 'HENRI EY PARKING ET EQUIPE MOBILE PATIENT LONG COURS', tva_defaut: '20' },
  { id: 246, numero: '702', nom: 'HENRI EY (BOX) 15 avenue de la Porte de Choisy 75013 PARIS', tva_defaut: '20' },
  { id: 247, numero: '106', nom: '12 Rue Cabanis', tva_defaut: '20' },
  { id: 248, numero: '548', nom: '130 BLVRD MACDO', tva_defaut: '20' },
  { id: 249, numero: '550', nom: 'Riquet', tva_defaut: '20' },
];

export const SEED_ENTREPRISES: Entreprise[] = [
  { id: 1, nom: '3 PROTECTION', specialite: '' },
  { id: 2, nom: 'A2A', specialite: '' },
  { id: 3, nom: 'A2C', specialite: '' },
  { id: 4, nom: 'AA PARIS', specialite: '' },
  { id: 5, nom: 'ABAC GROUPE CFH', specialite: '' },
  { id: 6, nom: 'ABM', specialite: '' },
  { id: 7, nom: 'ABOUCHARD MICHEL', specialite: '' },
  { id: 8, nom: 'ABPSI', specialite: '' },
  { id: 9, nom: 'AC2P', specialite: '' },
  { id: 10, nom: 'ACCEO', specialite: '' },
  { id: 11, nom: 'ACCES TP SAS', specialite: '' },
  { id: 12, nom: 'ACORUS PEINTISOL', specialite: '' },
  { id: 13, nom: 'ACOUSTIQUE ANTI BRUIT DIFFUSION (ISOLBRUIT)', specialite: '' },
  { id: 14, nom: 'ACTIF SIGNAL', specialite: '' },
  { id: 15, nom: 'ACTIV TP', specialite: '' },
  { id: 16, nom: 'ADENORM', specialite: '' },
  { id: 17, nom: 'AEC SA', specialite: '' },
  { id: 18, nom: 'AFP', specialite: '' },
  { id: 19, nom: 'AGENCE CUB', specialite: '' },
  { id: 20, nom: 'AGENCE DE L\'EAU ET SEINE NORMANDIE', specialite: '' },
  { id: 21, nom: 'AGIFEU', specialite: '' },
  { id: 22, nom: 'AGS', specialite: '' },
  { id: 23, nom: 'AIR LIQUIDE SANTE', specialite: '' },
  { id: 24, nom: 'ALEX PRO', specialite: '' },
  { id: 25, nom: 'ALMA', specialite: '' },
  { id: 26, nom: 'ALTEREA', specialite: '' },
  { id: 27, nom: 'ALTOR INDUSTRIE', specialite: '' },
  { id: 28, nom: 'ALVES LUIS', specialite: '' },
  { id: 29, nom: 'AM ESPACES VERTS', specialite: '' },
  { id: 30, nom: 'AN DIAG', specialite: '' },
  { id: 31, nom: 'ANTENNE 91', specialite: '' },
  { id: 32, nom: 'ANTOINE DUHAMEL PHOTOGRAPHY', specialite: '' },
  { id: 33, nom: 'APAVE', specialite: '' },
  { id: 34, nom: 'AQUAVEX', specialite: '' },
  { id: 35, nom: 'ARC 77', specialite: '' },
  { id: 36, nom: 'ARES SOLUTIONS', specialite: '' },
  { id: 37, nom: 'ARGENIUM', specialite: '' },
  { id: 38, nom: 'ARIA REPRO - FRANCE REPRO', specialite: '' },
  { id: 39, nom: 'ARJO FRANCE SAS', specialite: '' },
  { id: 40, nom: 'AROBASE SIGNALETIQUE', specialite: '' },
  { id: 41, nom: 'ASCAL', specialite: '' },
  { id: 42, nom: 'ASCOM HOLDING SA', specialite: '' },
  { id: 43, nom: 'ASKCO FR', specialite: '' },
  { id: 44, nom: 'ASSAINISSEMENT DE PARIS', specialite: '' },
  { id: 45, nom: 'ASSOCIATION CHANTIERS THERAPEUTIQUE', specialite: '' },
  { id: 46, nom: 'ATELIER BUISSONIER', specialite: '' },
  { id: 47, nom: 'ATELIER CIRCONFLEXE ARCHITECTES', specialite: '' },
  { id: 48, nom: 'AUGEOT MOTOCULTURE SERVICES', specialite: '' },
  { id: 49, nom: 'AUTOMATIC SYSTEMS', specialite: '' },
  { id: 50, nom: 'AUTOMATISME ET HYGIENE', specialite: '' },
  { id: 51, nom: 'AVISS', specialite: '' },
  { id: 52, nom: 'AVLS', specialite: '' },
  { id: 53, nom: 'AXE ETANCHEITE SARL', specialite: '' },
  { id: 54, nom: 'AXIANS UNIT GIE', specialite: '' },
  { id: 55, nom: 'BAELZ', specialite: '' },
  { id: 56, nom: 'BARCQUE CHARPENTE', specialite: '' },
  { id: 57, nom: 'BASSET JEAN-YVES', specialite: '' },
  { id: 58, nom: 'BEALAS ENERGIE SERVICES', specialite: '' },
  { id: 59, nom: 'BEG ENERGIE', specialite: '' },
  { id: 60, nom: 'BERTIN TECHNOLOGIE', specialite: '' },
  { id: 61, nom: 'BEST \' R', specialite: '' },
  { id: 62, nom: 'BGECO', specialite: '' },
  { id: 63, nom: 'BIM COLLAB', specialite: '' },
  { id: 64, nom: 'BLUELINEA', specialite: '' },
  { id: 65, nom: 'BOAMP', specialite: '' },
  { id: 66, nom: 'BOSCHER SIGNALETIQUE', specialite: '' },
  { id: 67, nom: 'BOTT SA', specialite: '' },
  { id: 68, nom: 'BS MOQUETTES', specialite: '' },
  { id: 69, nom: 'BSM', specialite: '' },
  { id: 70, nom: 'BSMG  LES TECHNICIENS DES FLUIDES', specialite: '' },
  { id: 71, nom: 'BUREAU VERITAS EXPLOITATION', specialite: '' },
  { id: 72, nom: 'BURLODGE', specialite: '' },
  { id: 73, nom: 'BWT', specialite: '' },
  { id: 74, nom: 'C.A.I.H', specialite: '' },
  { id: 75, nom: 'C.I.TECH', specialite: '' },
  { id: 76, nom: 'CAMEO', specialite: '' },
  { id: 77, nom: 'CAPITAINE', specialite: '' },
  { id: 78, nom: 'CCR', specialite: '' },
  { id: 79, nom: 'CEDEO', specialite: '' },
  { id: 80, nom: 'CEGELEC', specialite: '' },
  { id: 81, nom: 'CERADEL AUBER', specialite: '' },
  { id: 82, nom: 'CERECO', specialite: '' },
  { id: 83, nom: 'CERTIVEA', specialite: '' },
  { id: 84, nom: 'CG2I', specialite: '' },
  { id: 85, nom: 'CHEVILLON FREDERIC', specialite: '' },
  { id: 86, nom: 'CHOUFFOT', specialite: '' },
  { id: 87, nom: 'CI TECH', specialite: '' },
  { id: 88, nom: 'CIEC', specialite: '' },
  { id: 89, nom: 'CNTE', specialite: '' },
  { id: 90, nom: 'COGIS NETWORKS', specialite: '' },
  { id: 91, nom: 'COLAS ILE-DE-FRANCE NORMANDIE', specialite: '' },
  { id: 92, nom: 'CONNEXING SAS.', specialite: '' },
  { id: 93, nom: 'CONSEIL NATIONAL DE L\'ORDRE DES ARCHITECTES', specialite: '' },
  { id: 94, nom: 'COPTOS PRITING SOLUTIONS', specialite: '' },
  { id: 95, nom: 'CORONA MEDICAL', specialite: '' },
  { id: 96, nom: 'COUGNAUD', specialite: '' },
  { id: 97, nom: 'CPCU', specialite: '' },
  { id: 98, nom: 'CREDIT AGRICOLE LEASING & FACTORING', specialite: '' },
  { id: 99, nom: 'CRM', specialite: '' },
  { id: 100, nom: 'CS INGENIERIE', specialite: '' },
  { id: 101, nom: 'D&K GMBH & CO. KG', specialite: '' },
  { id: 102, nom: 'DALKIA', specialite: '' },
  { id: 103, nom: 'DBP', specialite: '' },
  { id: 104, nom: 'DC INGENIERIE SARL', specialite: '' },
  { id: 105, nom: 'DDN', specialite: '' },
  { id: 106, nom: 'DECATHLON PRO', specialite: '' },
  { id: 107, nom: 'DEKRA', specialite: '' },
  { id: 108, nom: 'DELCLOY', specialite: '' },
  { id: 109, nom: 'DELOSTAL ET THIBAULT', specialite: '' },
  { id: 110, nom: 'DELTA T', specialite: '' },
  { id: 111, nom: 'DEMATIS', specialite: '' },
  { id: 112, nom: 'DESMAREZ', specialite: '' },
  { id: 113, nom: 'DFM RENOVATION', specialite: '' },
  { id: 114, nom: 'DIAGOBAT', specialite: '' },
  { id: 115, nom: 'DIDAXIS', specialite: '' },
  { id: 116, nom: 'DINAMIC', specialite: '' },
  { id: 117, nom: 'DOM Métalux', specialite: '' },
  { id: 118, nom: 'DOMMERY', specialite: '' },
  { id: 119, nom: 'DORMAKABA', specialite: '' },
  { id: 120, nom: 'DPIM', specialite: '' },
  { id: 121, nom: 'driot', specialite: '' },
  { id: 122, nom: 'DUPORT 91', specialite: '' },
  { id: 123, nom: 'DUVAL MESSIEN', specialite: '' },
  { id: 124, nom: 'E MAGING COMPUTER France', specialite: '' },
  { id: 125, nom: 'EARTH AVOCATS', specialite: '' },
  { id: 126, nom: 'EAU DE PARIS', specialite: '' },
  { id: 127, nom: 'EAU SEINE NORMANDIE', specialite: '' },
  { id: 128, nom: 'EFFICIO', specialite: '' },
  { id: 129, nom: 'efficium workteam', specialite: '' },
  { id: 130, nom: 'EFICIUM WORKTEAM PARIS', specialite: '' },
  { id: 131, nom: 'EGA COMMUNICATION SECURITE', specialite: '' },
  { id: 132, nom: 'EGDC', specialite: '' },
  { id: 133, nom: 'EKOPOLIS', specialite: '' },
  { id: 134, nom: 'ELECTROCLASS', specialite: '' },
  { id: 135, nom: 'ELIEZ', specialite: '' },
  { id: 136, nom: 'EMERGENCE', specialite: '' },
  { id: 137, nom: 'EMMAUS', specialite: '' },
  { id: 138, nom: 'EN OM FRA', specialite: '' },
  { id: 139, nom: 'ENEDIS', specialite: '' },
  { id: 140, nom: 'ENERBRAIN', specialite: '' },
  { id: 141, nom: 'ENGIE AXIMA', specialite: '' },
  { id: 142, nom: 'ENGIE SOLUTIONS (INEO DIGITALE)', specialite: '' },
  { id: 143, nom: 'ENJOY YOUR SPACE', specialite: '' },
  { id: 144, nom: 'ENODIS', specialite: '' },
  { id: 145, nom: 'ERGELEC', specialite: '' },
  { id: 146, nom: 'ESPACES TP', specialite: '' },
  { id: 147, nom: 'ETAP', specialite: '' },
  { id: 148, nom: 'EUROFEU SERVICES', specialite: '' },
  { id: 149, nom: 'EUROFINS', specialite: '' },
  { id: 150, nom: 'EUROTEC', specialite: '' },
  { id: 151, nom: 'EXOVISION', specialite: '' },
  { id: 152, nom: 'F3DF', specialite: '' },
  { id: 153, nom: 'FICHET', specialite: '' },
  { id: 154, nom: 'FOUSSIER', specialite: '' },
  { id: 155, nom: 'FRANCOIS ROBIN', specialite: '' },
  { id: 156, nom: 'FRANKLIN ENERGIE', specialite: '' },
  { id: 157, nom: 'FROID 77', specialite: '' },
  { id: 158, nom: 'FTP', specialite: '' },
  { id: 159, nom: 'FTS BAT', specialite: '' },
  { id: 160, nom: 'FULGONI', specialite: '' },
  { id: 161, nom: 'GA IDF', specialite: '' },
  { id: 162, nom: 'GAZPROTEC', specialite: '' },
  { id: 163, nom: 'GCS UNIHA', specialite: '' },
  { id: 164, nom: 'GEOLIA', specialite: '' },
  { id: 165, nom: 'GEOMETRIC', specialite: '' },
  { id: 166, nom: 'GEPSA', specialite: '' },
  { id: 167, nom: 'GERCOM', specialite: '' },
  { id: 168, nom: 'GETINGE FRANCE', specialite: '' },
  { id: 169, nom: 'GEZE', specialite: '' },
  { id: 170, nom: 'GRDF', specialite: '' },
  { id: 171, nom: 'GROUPE MONITEUR', specialite: '' },
  { id: 172, nom: 'GROUPE SECHE', specialite: '' },
  { id: 173, nom: 'GRTGAZ', specialite: '' },
  { id: 174, nom: 'GSI', specialite: '' },
  { id: 175, nom: 'GTA GEOMETRES EXPERTS', specialite: '' },
  { id: 176, nom: 'GUILBERT', specialite: '' },
  { id: 177, nom: 'H CALL SYSTHEMS', specialite: '' },
  { id: 178, nom: 'HAMMOU', specialite: '' },
  { id: 179, nom: 'HANNY', specialite: '' },
  { id: 180, nom: 'HENINE ELECTRIQUE', specialite: '' },
  { id: 181, nom: 'HILLROM', specialite: '' },
  { id: 182, nom: 'HOBART', specialite: '' },
  { id: 183, nom: 'HORELEC', specialite: '' },
  { id: 184, nom: 'HQ AIR', specialite: '' },
  { id: 185, nom: 'I TECH TRANSFERT', specialite: '' },
  { id: 186, nom: 'ID CAPTURE VISIOBAT', specialite: '' },
  { id: 187, nom: 'IMPACT', specialite: '' },
  { id: 188, nom: 'IMPAIROUSSOT', specialite: '' },
  { id: 189, nom: 'INEO DIGITAL', specialite: '' },
  { id: 190, nom: 'INGENIERIE CEM', specialite: '' },
  { id: 191, nom: 'INITIATIVES SOLIDAIRES', specialite: '' },
  { id: 192, nom: 'INTEGRIP', specialite: '' },
  { id: 193, nom: 'IRELEM', specialite: '' },
  { id: 194, nom: 'ITG', specialite: '' },
  { id: 195, nom: 'IXO ENGINEERING (ANCIEN ABAC)', specialite: '' },
  { id: 196, nom: 'JAKOB', specialite: '' },
  { id: 197, nom: 'JARDINS LOISIRS MICHELET', specialite: '' },
  { id: 198, nom: 'JEZEQUEL GRUEL ET ASSOCIES', specialite: '' },
  { id: 199, nom: 'JMD SYSTEMES', specialite: '' },
  { id: 200, nom: 'JOURNAUX OFFICIELS', specialite: '' },
  { id: 201, nom: 'KARCHER', specialite: '' },
  { id: 202, nom: 'KELEC', specialite: '' },
  { id: 203, nom: 'KEP LOT', specialite: '' },
  { id: 204, nom: 'KLEON', specialite: '' },
  { id: 205, nom: 'KOHLER', specialite: '' },
  { id: 206, nom: 'L3A AIR', specialite: '' },
  { id: 207, nom: 'L3A DIAG', specialite: '' },
  { id: 208, nom: 'LA GENERALE INDUSTRIE', specialite: '' },
  { id: 209, nom: 'LA LOUISIANE', specialite: '' },
  { id: 210, nom: 'LABYS', specialite: '' },
  { id: 211, nom: 'LB DIAG 95', specialite: '' },
  { id: 212, nom: 'LEA ARCHITECTES', specialite: '' },
  { id: 213, nom: 'LEGALLAIS', specialite: '' },
  { id: 214, nom: 'LEGRAND ENERGIE SOLUTIONS', specialite: '' },
  { id: 215, nom: 'LERAU', specialite: '' },
  { id: 216, nom: 'LES TULIPES DE FRANCE', specialite: '' },
  { id: 217, nom: 'L\'ESPRIT DU VAN', specialite: '' },
  { id: 218, nom: 'L\'ETINCELLE', specialite: '' },
  { id: 219, nom: 'LEXIMPACT', specialite: '' },
  { id: 220, nom: 'LF SYSTEMES', specialite: '' },
  { id: 221, nom: 'LFV', specialite: '' },
  { id: 222, nom: 'LINET', specialite: '' },
  { id: 223, nom: 'LM INGENIERIE', specialite: '' },
  { id: 224, nom: 'LT PLOMBERIE CHAUFFAGE', specialite: '' },
  { id: 225, nom: 'LTDF DES FLUIDES', specialite: '' },
  { id: 226, nom: 'LUVELEC', specialite: '' },
  { id: 227, nom: 'LVCOM', specialite: '' },
  { id: 228, nom: 'M.E.S DISTRIBUTION', specialite: '' },
  { id: 229, nom: 'M² LA LETTRE', specialite: '' },
  { id: 230, nom: 'MAIRIE DE PARIS', specialite: '' },
  { id: 231, nom: 'MANUTAN COLLECTIVITES', specialite: '' },
  { id: 232, nom: 'MARCOS VINUESA', specialite: '' },
  { id: 233, nom: 'MARINER 3S', specialite: '' },
  { id: 234, nom: 'MASSIMO LOMBARDI', specialite: '' },
  { id: 235, nom: 'MASTERFRISOS', specialite: '' },
  { id: 236, nom: 'MCFE', specialite: '' },
  { id: 237, nom: 'MEIKO FRANCE SAS', specialite: '' },
  { id: 238, nom: 'MEL ET KIO', specialite: '' },
  { id: 239, nom: 'MESREL', specialite: '' },
  { id: 240, nom: 'METALUX', specialite: '' },
  { id: 241, nom: 'METASSISTANCE', specialite: '' },
  { id: 242, nom: 'MG RENOVATION', specialite: '' },
  { id: 243, nom: 'MID', specialite: '' },
  { id: 244, nom: 'MIELE', specialite: '' },
  { id: 245, nom: 'MINELIS', specialite: '' },
  { id: 246, nom: 'MIROITERIE PERUCCA', specialite: '' },
  { id: 247, nom: 'MMO INGENIERIE', specialite: '' },
  { id: 248, nom: 'MONTIEGE PRECISION MECANIQUE', specialite: '' },
  { id: 249, nom: 'MUTUELLE DES ARCHITECTES FRANCAIS', specialite: '' },
  { id: 250, nom: 'NATURAL TOUCH', specialite: '' },
  { id: 251, nom: 'NESPRESSO', specialite: '' },
  { id: 252, nom: 'NET COLLECTIVITES', specialite: '' },
  { id: 253, nom: 'NEXITY PARIS NATION', specialite: '' },
  { id: 254, nom: 'Nilfisk', specialite: '' },
  { id: 255, nom: 'NORBA', specialite: '' },
  { id: 256, nom: 'NORDTHERM', specialite: '' },
  { id: 257, nom: 'NTSI SUD', specialite: '' },
  { id: 258, nom: 'OASIIS', specialite: '' },
  { id: 259, nom: 'OCTALINO', specialite: '' },
  { id: 260, nom: 'OFP CALIPAGE', specialite: '' },
  { id: 261, nom: 'ORDRE DES ARCHITECTES', specialite: '' },
  { id: 262, nom: 'OTIS', specialite: '' },
  { id: 263, nom: 'OUEST DIFFUSION SANTE', specialite: '' },
  { id: 264, nom: 'PAOLO BATTISTEL', specialite: '' },
  { id: 265, nom: 'PARGADE ARCHITECTES', specialite: '' },
  { id: 266, nom: 'PASCAL LOUVION', specialite: '' },
  { id: 267, nom: 'PATTOU S.A.S', specialite: '' },
  { id: 268, nom: 'PAYBYPHONE', specialite: '' },
  { id: 269, nom: 'PB MAINTENANCE', specialite: '' },
  { id: 270, nom: 'PEDRAZZINI', specialite: '' },
  { id: 271, nom: 'PEINTISOL', specialite: '' },
  { id: 272, nom: 'PEPINIERES ALLAVOINE', specialite: '' },
  { id: 273, nom: 'PETER LAVEM', specialite: '' },
  { id: 274, nom: 'PETRARQUE', specialite: '' },
  { id: 275, nom: 'PHB', specialite: '' },
  { id: 276, nom: 'PICARD', specialite: '' },
  { id: 277, nom: 'PIXEL 451', specialite: '' },
  { id: 278, nom: 'PORTALP', specialite: '' },
  { id: 279, nom: 'PPS', specialite: '' },
  { id: 280, nom: 'PREMYS', specialite: '' },
  { id: 281, nom: 'PRODESIGN', specialite: '' },
  { id: 282, nom: 'PROMESSE DE FLEURS', specialite: '' },
  { id: 283, nom: 'PROTECTA 24', specialite: '' },
  { id: 284, nom: 'PRS', specialite: '' },
  { id: 285, nom: 'PUZZLE', specialite: '' },
  { id: 286, nom: 'RCI GROUP', specialite: '' },
  { id: 287, nom: 'RECORDEM MAGDALEMA', specialite: '' },
  { id: 288, nom: 'REGIS GUIGNARD', specialite: '' },
  { id: 289, nom: 'REHLKO', specialite: '' },
  { id: 290, nom: 'REMIX', specialite: '' },
  { id: 291, nom: 'REMOVE', specialite: '' },
  { id: 292, nom: 'RESAH', specialite: '' },
  { id: 293, nom: 'REXEL', specialite: '' },
  { id: 294, nom: 'RF SOLUTIONS', specialite: '' },
  { id: 295, nom: 'RISK CONTROL', specialite: '' },
  { id: 296, nom: 'ROLAND DG FRANCE', specialite: '' },
  { id: 297, nom: 'ROUSSEL CENTRE STORES FERMETURES', specialite: '' },
  { id: 298, nom: 'RS PRO (Radio Spares)', specialite: '' },
  { id: 299, nom: 'RSK', specialite: '' },
  { id: 300, nom: 'SAEMES', specialite: '' },
  { id: 301, nom: 'SAHP', specialite: '' },
  { id: 302, nom: 'SAKKARAH', specialite: '' },
  { id: 303, nom: 'SALTO', specialite: '' },
  { id: 304, nom: 'SAMUEL DELMAS', specialite: '' },
  { id: 305, nom: 'SARL MAISONS DANS LES ARBRES', specialite: '' },
  { id: 306, nom: 'SAS ASTERM', specialite: '' },
  { id: 307, nom: 'SAVPRO', specialite: '' },
  { id: 308, nom: 'SCAN FACTORY', specialite: '' },
  { id: 309, nom: 'SCEA FANFELLE GAUSSENS', specialite: '' },
  { id: 310, nom: 'SCHNEIDER', specialite: '' },
  { id: 311, nom: 'SCHNEIDER ELECTRIC', specialite: '' },
  { id: 312, nom: 'SCRS', specialite: '' },
  { id: 313, nom: 'SDA', specialite: '' },
  { id: 314, nom: 'SEBAN&ASSOCIES', specialite: '' },
  { id: 315, nom: 'SECHE', specialite: '' },
  { id: 316, nom: 'SECTRA', specialite: '' },
  { id: 317, nom: 'SECURITAS DIRECT SAS', specialite: '' },
  { id: 318, nom: 'SEGAT', specialite: '' },
  { id: 319, nom: 'SERMET', specialite: '' },
  { id: 320, nom: 'SERRURERIE RENOVATION MAINTENANCE', specialite: '' },
  { id: 321, nom: 'SERSI SYSTEME', specialite: '' },
  { id: 322, nom: 'SERTAC', specialite: '' },
  { id: 323, nom: 'SERVICE PILOT', specialite: '' },
  { id: 324, nom: 'SERVISTORE', specialite: '' },
  { id: 325, nom: 'SESEM', specialite: '' },
  { id: 326, nom: 'SFR BUSNESS', specialite: '' },
  { id: 327, nom: 'SGDS', specialite: '' },
  { id: 328, nom: 'SHB ELECTRIC', specialite: '' },
  { id: 329, nom: 'Sider', specialite: '' },
  { id: 330, nom: 'SIEMENS SAS', specialite: '' },
  { id: 331, nom: 'SILCA', specialite: '' },
  { id: 332, nom: 'SIMONS VOSS', specialite: '' },
  { id: 333, nom: 'SITHEC', specialite: '' },
  { id: 334, nom: 'SMA', specialite: '' },
  { id: 335, nom: 'SNEF', specialite: '' },
  { id: 336, nom: 'SOCOMEC', specialite: '' },
  { id: 337, nom: 'SOCOTEC CONSTRUCTION', specialite: '' },
  { id: 338, nom: 'SOFINOR', specialite: '' },
  { id: 339, nom: 'SOGEDIS', specialite: '' },
  { id: 340, nom: 'SOGOBA', specialite: '' },
  { id: 341, nom: 'SOLAIRE THERMIQUE FRANCE', specialite: '' },
  { id: 342, nom: 'SOMATICO', specialite: '' },
  { id: 343, nom: 'SOPRONEG', specialite: '' },
  { id: 344, nom: 'SOTERKENOS', specialite: '' },
  { id: 345, nom: 'SOTRAFRAN', specialite: '' },
  { id: 346, nom: 'SPIE FACILITIES', specialite: '' },
  { id: 347, nom: 'SRM', specialite: '' },
  { id: 348, nom: 'STPEE', specialite: '' },
  { id: 349, nom: 'SUEZ EAU FRANCE', specialite: '' },
  { id: 350, nom: 'SYCLOPE ELECTRONIQUE', specialite: '' },
  { id: 351, nom: 'SYLIFT', specialite: '' },
  { id: 352, nom: 'SYNTHE PROTECT', specialite: '' },
  { id: 353, nom: 'T3E', specialite: '' },
  { id: 354, nom: 'TBM', specialite: '' },
  { id: 355, nom: 'TEDDINGTON', specialite: '' },
  { id: 356, nom: 'TERNEO', specialite: '' },
  { id: 357, nom: 'TERRASOL', specialite: '' },
  { id: 358, nom: 'TESORA', specialite: '' },
  { id: 359, nom: 'TESTO', specialite: '' },
  { id: 360, nom: 'TIBBLOC', specialite: '' },
  { id: 361, nom: 'TOLIX', specialite: '' },
  { id: 362, nom: 'TRANE RENTAL SERVICES', specialite: '' },
  { id: 363, nom: 'TRANSFO SERVICES', specialite: '' },
  { id: 364, nom: 'TYYNY', specialite: '' },
  { id: 365, nom: 'UGAP', specialite: '' },
  { id: 366, nom: 'UGGC AVOCATS', specialite: '' },
  { id: 367, nom: 'US&CO', specialite: '' },
  { id: 368, nom: 'UTB', specialite: '' },
  { id: 369, nom: 'VEOLIA EAU D\'ILE DE FRANCE SNC', specialite: '' },
  { id: 370, nom: 'VÉRONIQUE PARISOT', specialite: '' },
  { id: 371, nom: 'VIGI SECURITE', specialite: '' },
  { id: 372, nom: 'VISIOBAT', specialite: '' },
  { id: 373, nom: 'VITICABROL', specialite: '' },
  { id: 374, nom: 'ZENITEL', specialite: '' },
  { id: 375, nom: 'LE FROID BORNET', specialite: '' },
  { id: 376, nom: 'LONG ENERGIES (ex Delostal & Thibault)', specialite: '' },
  { id: 377, nom: 'FOURNIRESTO', specialite: '' },
  { id: 378, nom: 'EBERHARDT', specialite: '' },
  { id: 379, nom: 'KML DEPANNAGE', specialite: '' },
  { id: 380, nom: 'CORAL', specialite: '' },
  { id: 381, nom: 'IDF GROUX', specialite: '' },
  { id: 382, nom: 'VETILABEL', specialite: '' },
  { id: 383, nom: 'electroclass', specialite: '' },
];

export const SEED_MARCHES: Marche[] = [
  { id: 1, numero: '2019-0749', entreprise: 'CBC', objet: 'Maintenance' },
  { id: 2, numero: '2019-0883', entreprise: 'I TECH TRANSFERT - I2T', objet: 'Déménagement' },
  { id: 3, numero: '2019-1017', entreprise: 'SIEMENS', objet: 'SSI' },
  { id: 4, numero: '2020-0577', entreprise: 'SCHNEIDER ELECTRIC France', objet: 'Electricité' },
  { id: 5, numero: '2020-0801', entreprise: 'SAS LEGALLAIS', objet: 'Quincaillerie' },
  { id: 6, numero: '2021-0374', entreprise: 'CIEC', objet: 'CVC' },
  { id: 7, numero: '2021-0375', entreprise: 'OTIS', objet: 'Ascenseurs' },
  { id: 8, numero: '2021-0610', entreprise: 'ACCEO', objet: 'Ascenseurs' },
  { id: 9, numero: '2021-0790', entreprise: 'ABAC', objet: 'GTB' },
  { id: 10, numero: '2021-0834', entreprise: 'PRS', objet: 'Anti-agression' },
  { id: 11, numero: '2021-0855', entreprise: 'ARIA REPRO', objet: 'Signalétique' },
  { id: 12, numero: '2021-0899', entreprise: 'AIR LIQUIDE SANTE France', objet: 'Fluides médicaux' },
  { id: 13, numero: '2021-0937', entreprise: 'BWT France', objet: 'Eau' },
  { id: 14, numero: '2022-0179', entreprise: 'SIEMENS', objet: 'SSI' },
  { id: 15, numero: '2022-0304', entreprise: 'SERVICE PILOTE TECHNOLOGIES SAS', objet: 'Supervision' },
  { id: 16, numero: '2022-0406', entreprise: 'VIGISECURITE', objet: 'Gardiennage et surveillance' },
  { id: 17, numero: '2022-0431', entreprise: 'AM ESPACES VERTS', objet: 'Espaces verts' },
  { id: 18, numero: '2022-0463', entreprise: 'ARC 77', objet: 'CSPS' },
  { id: 19, numero: '2022-0464', entreprise: 'ARIA REPRO', objet: 'Reprographie' },
  { id: 20, numero: '2022-0917', entreprise: 'BWT France', objet: 'Eau' },
  { id: 21, numero: '2023-0055', entreprise: 'C.I.TECH', objet: 'CVC' },
  { id: 22, numero: '2023-0056', entreprise: 'ANTAGUA', objet: 'CVC' },
  { id: 23, numero: '2023-0057', entreprise: 'SERMET', objet: 'CVC' },
  { id: 24, numero: '2023-0058', entreprise: 'C.I.TECH', objet: 'Electricité' },
  { id: 25, numero: '2023-0059', entreprise: 'T3E IDF', objet: 'Electricité' },
  { id: 26, numero: '2023-0077', entreprise: 'ATELIER CIRCONFLEXE ARCHITECTES', objet: 'Architectes' },
  { id: 27, numero: '2023-0078', entreprise: 'EMERGENCE ARCHITECTES', objet: 'Architectes' },
  { id: 28, numero: '2023-0079', entreprise: 'L.E.A ARCHITECTES', objet: 'Architectes' },
  { id: 29, numero: '2023-0081', entreprise: 'EUROFEU SOLUTIONS', objet: 'SSI' },
  { id: 30, numero: '2023-0082', entreprise: 'EUROFEU SOLUTIONS', objet: 'SSI' },
  { id: 31, numero: '2023-0083', entreprise: 'EUROFEU SOLUTIONS', objet: 'SSI' },
  { id: 32, numero: '2023-0106', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 33, numero: '2023-0107', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 34, numero: '2023-0108', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 35, numero: '2023-0109', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 36, numero: '2023-0110', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 37, numero: '2023-0111', entreprise: 'APAVE EXPLOITATION FRANCE', objet: 'Contrôle réglementaire des installations techniques' },
  { id: 38, numero: '2023-0169', entreprise: 'DELCLOY', objet: 'Echafaudage - Ravalement des façades' },
  { id: 39, numero: '2023-0170', entreprise: 'SRM', objet: 'Métallerie' },
  { id: 40, numero: '2023-0328', entreprise: 'S.E.L.A.S GTA GEOMETRE EXPERT', objet: 'Topographie' },
  { id: 41, numero: '2023-0340', entreprise: 'ALMA', objet: 'Maçonnerie - carrelage' },
  { id: 42, numero: '2023-0341', entreprise: 'EGDC', objet: 'Maçonnerie - carrelage' },
  { id: 43, numero: '2023-0342', entreprise: 'EGDC', objet: 'Maçonnerie - carrelage' },
  { id: 44, numero: '2023-0343', entreprise: 'ALMA', objet: 'Maçonnerie - carrelage' },
  { id: 45, numero: '2023-0344', entreprise: 'EGDC', objet: 'Maçonnerie - carrelage' },
  { id: 46, numero: '2023-0345', entreprise: 'ELIEZ', objet: 'Peinture' },
  { id: 47, numero: '2023-0346', entreprise: 'PEINTISOL', objet: 'Peinture' },
  { id: 48, numero: '2023-0347', entreprise: 'PEINTISOL', objet: 'Peinture' },
  { id: 49, numero: '2023-0348', entreprise: 'ELIEZ', objet: 'Peinture' },
  { id: 50, numero: '2023-0349', entreprise: 'PEINTISOL', objet: 'Peinture' },
  { id: 51, numero: '2023-0350', entreprise: 'BSM', objet: 'Faux plafond' },
  { id: 52, numero: '2023-0351', entreprise: 'PRS', objet: 'Faux plafond' },
  { id: 53, numero: '2023-0352', entreprise: 'PRS', objet: 'Faux plafond' },
  { id: 54, numero: '2023-0353', entreprise: 'BSM', objet: 'Faux plafond' },
  { id: 55, numero: '2023-0354', entreprise: 'PRS', objet: 'Faux plafond' },
  { id: 56, numero: '2023-0355', entreprise: 'ALVES', objet: 'Menuiseries' },
  { id: 57, numero: '2023-0356', entreprise: 'PRS', objet: 'Menuiseries' },
  { id: 58, numero: '2023-0357', entreprise: 'PRS', objet: 'Menuiseries' },
  { id: 59, numero: '2023-0358', entreprise: 'ALVES', objet: 'Menuiseries' },
  { id: 60, numero: '2023-0359', entreprise: 'PRS', objet: 'Menuiseries' },
  { id: 61, numero: '2023-0360', entreprise: 'L\'ART ET LE BOIS', objet: 'Paillasses' },
  { id: 62, numero: '2023-0361', entreprise: 'AC2P', objet: 'Agencement' },
  { id: 63, numero: '2023-0362', entreprise: 'AC2P', objet: 'Agencement' },
  { id: 64, numero: '2023-0363', entreprise: 'AC2P', objet: 'Agencement' },
  { id: 65, numero: '2023-0364', entreprise: 'AC2P', objet: 'Agencement' },
  { id: 66, numero: '2023-0365', entreprise: 'AC2P', objet: 'Agencement' },
  { id: 67, numero: '2023-0366', entreprise: 'ELIEZ', objet: 'Sols souples' },
  { id: 68, numero: '2023-0367', entreprise: 'PEINTISOL', objet: 'Sols souples' },
  { id: 69, numero: '2023-0368', entreprise: 'PEINTISOL', objet: 'Sols souples' },
  { id: 70, numero: '2023-0369', entreprise: 'ELIEZ', objet: 'Sols souples' },
  { id: 71, numero: '2023-0370', entreprise: 'PEINTISOL', objet: 'Sols souples' },
  { id: 72, numero: '2023-0371', entreprise: 'SRM', objet: 'Vitrerie' },
  { id: 73, numero: '2023-0372', entreprise: 'UTB', objet: 'Couverture' },
  { id: 74, numero: '2023-0373', entreprise: 'LA LOUISIANE', objet: 'Couverture' },
  { id: 75, numero: '2023-0374', entreprise: 'LA LOUISIANE', objet: 'Couverture' },
  { id: 76, numero: '2023-0375', entreprise: 'UTB', objet: 'Couverture' },
  { id: 77, numero: '2023-0376', entreprise: 'LA LOUISIANE', objet: 'Couverture' },
  { id: 78, numero: '2023-0377', entreprise: 'UTB', objet: 'Etanchéité' },
  { id: 79, numero: '2023-0378', entreprise: 'MFCE', objet: 'Etanchéité' },
  { id: 80, numero: '2023-0379', entreprise: 'MFCE', objet: 'Etanchéité' },
  { id: 81, numero: '2023-0380', entreprise: 'UTB', objet: 'Etanchéité' },
  { id: 82, numero: '2023-0381', entreprise: 'MFCE', objet: 'Etanchéité' },
  { id: 83, numero: '2023-0382', entreprise: 'STPEE', objet: 'Electricité' },
  { id: 84, numero: '2023-0383', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 85, numero: '2023-0384', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 86, numero: '2023-0385', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 87, numero: '2023-0386', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 88, numero: '2023-0388', entreprise: 'BSMG LTDF', objet: 'CVC' },
  { id: 89, numero: '2023-0389', entreprise: 'BSMG LTDF', objet: 'CVC' },
  { id: 90, numero: '2023-0390', entreprise: 'SCHNEIDER', objet: 'CVC' },
  { id: 91, numero: '2023-0391', entreprise: 'SCHNEIDER', objet: 'CVC' },
  { id: 92, numero: '2023-0393', entreprise: 'BSMG LTDF', objet: 'Plomberie' },
  { id: 93, numero: '2023-0394', entreprise: 'BSMG LTDF', objet: 'Plomberie' },
  { id: 94, numero: '2023-0395', entreprise: 'SCHNEIDER', objet: 'Plomberie' },
  { id: 95, numero: '2023-0396', entreprise: 'SCHNEIDER', objet: 'Plomberie' },
  { id: 96, numero: '2023-0397', entreprise: 'Driot', objet: 'Fluides médicaux' },
  { id: 97, numero: '2023-0398', entreprise: 'ABPSI', objet: 'Stores' },
  { id: 98, numero: '2023-0399', entreprise: 'PREMYS', objet: 'Désamiantage' },
  { id: 99, numero: '2023-0400', entreprise: 'DOMMERY', objet: 'Désamiantage' },
  { id: 100, numero: '2023-0401', entreprise: 'REMOVE', objet: 'Désamiantage' },
  { id: 101, numero: '2023-0402', entreprise: 'PREMYS', objet: 'Désamiantage' },
  { id: 102, numero: '2023-0403', entreprise: 'REMOVE', objet: 'Désamiantage' },
  { id: 103, numero: '2023-0406', entreprise: 'ACCES TP', objet: 'VRD' },
  { id: 104, numero: '2023-0408', entreprise: 'ACCES TP', objet: 'VRD' },
  { id: 105, numero: '2023-0409', entreprise: 'EFFICIUM WORKTEAM', objet: 'Lessivage' },
  { id: 106, numero: '2023-0410', entreprise: 'EUROFINS HYGIENE HOSPITALIERE NORD', objet: 'Potabilité eau' },
  { id: 107, numero: '2023-0467', entreprise: 'IMPAIR ROUSSOT', objet: 'Fermetures automatiques' },
  { id: 108, numero: '2023-0527', entreprise: 'RISK CONTROL', objet: 'Bureau de contôle' },
  { id: 109, numero: '2023-0573', entreprise: 'SADE', objet: 'Disconnecteurs' },
  { id: 110, numero: '2023-0596', entreprise: 'FULGONI', objet: 'CVC' },
  { id: 111, numero: '2023-0597', entreprise: 'RISK CONTROL', objet: 'Bureau de contôle' },
  { id: 112, numero: '2023-0599', entreprise: 'CS INGENIERIE', objet: 'SSI' },
  { id: 113, numero: '2023-0624', entreprise: 'EFFICIO', objet: 'SSI' },
  { id: 114, numero: '2023-0629', entreprise: 'ANTEA GROUP', objet: 'Eau pluviales' },
  { id: 115, numero: '2023-0668', entreprise: 'CARA', objet: 'Main courante' },
  { id: 116, numero: '2023-0720', entreprise: 'I TECH TRANSFERT - I2T', objet: 'Déménagement' },
  { id: 117, numero: '2023-0809', entreprise: 'SOCOMEC', objet: 'Onduleurs' },
  { id: 118, numero: '2023-0840', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 119, numero: '2023-0841', entreprise: 'SDMO INDUSTRIES', objet: 'Groupes électrogènes' },
  { id: 120, numero: '2023-0842', entreprise: 'AVISS SERVICES', objet: 'SSI' },
  { id: 121, numero: '2024-0191', entreprise: 'ETMB', objet: 'Gros œuvre - CEA' },
  { id: 122, numero: '2024-0192', entreprise: 'SRM', objet: 'MEXT - Metallerie' },
  { id: 123, numero: '2024-0193', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 124, numero: '2024-0194', entreprise: 'AIREOL', objet: 'CVC Plomberie' },
  { id: 125, numero: '2024-0195', entreprise: 'BSM', objet: 'Agencements' },
  { id: 126, numero: '2024-0196', entreprise: 'TBES', objet: 'Electricité' },
  { id: 127, numero: '2024-0197', entreprise: 'BSMG-LTDF', objet: 'CVC Plomberie' },
  { id: 128, numero: '2024-0198', entreprise: 'BSM', objet: 'Agencements' },
  { id: 129, numero: '2024-0199', entreprise: 'TBES', objet: 'Electricité' },
  { id: 130, numero: '2024-0200', entreprise: 'BSMG-LTDF', objet: 'CVC Plomberie' },
  { id: 131, numero: '2024-0240', entreprise: 'LEON GROSSE', objet: 'Gros œuvre - CEA' },
  { id: 132, numero: '2024-0241', entreprise: 'LEON GROSSE', objet: 'MEXT - Metallerie' },
  { id: 133, numero: '2024-0242', entreprise: 'CEGELEC', objet: 'Electrcité' },
  { id: 134, numero: '2024-0243', entreprise: 'MCFE', objet: 'CVC Plomberie' },
  { id: 135, numero: '2024-0244', entreprise: 'GPF', objet: 'Fluides médicaux' },
  { id: 136, numero: '2024-0373', entreprise: 'SEGAT', objet: 'Gestion des actifs immobiliers' },
  { id: 137, numero: '2024-0374', entreprise: 'SRM', objet: 'Metallerie' },
  { id: 138, numero: '2024-0375', entreprise: 'SRM', objet: 'Metallerie' },
  { id: 139, numero: '2024-0376', entreprise: 'SRM', objet: 'Metallerie' },
  { id: 140, numero: '2024-0377', entreprise: 'SRM', objet: 'Metallerie' },
  { id: 141, numero: '2024-0378', entreprise: 'SRM', objet: 'Metallerie' },
  { id: 142, numero: '2024-0416', entreprise: 'ARGENIUM', objet: 'Assistance et AMO Amiante - Plomb' },
  { id: 143, numero: '2024-0654', entreprise: 'DALKIA', objet: 'CVC' },
  { id: 144, numero: '2024-0655', entreprise: 'TERIDEAL SAS', objet: 'VRD' },
  { id: 145, numero: '2024-0675', entreprise: 'ID CAPTURE', objet: 'Service electronique' },
  { id: 146, numero: '2024-0700', entreprise: 'VIOLA', objet: 'Eclairage' },
  { id: 147, numero: '2024-0724', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 148, numero: '2024-0749', entreprise: 'AC Environnement', objet: 'Diagnostic immobilier' },
  { id: 149, numero: '2024-0750', entreprise: 'Quallitat Expertises', objet: 'Diagnostic immobilier' },
  { id: 150, numero: '2024-0751', entreprise: 'Leximpact', objet: 'Diagnostic immobilier' },
  { id: 151, numero: '2024-0752', entreprise: 'AC Environnement', objet: 'Diagnostic immobilier' },
  { id: 152, numero: '2024-0753', entreprise: 'Quallitat Expertises', objet: 'Diagnostic immobilier' },
  { id: 153, numero: '2024-0754', entreprise: 'FMDC Diagnostics', objet: 'Diagnostic immobilier' },
  { id: 154, numero: '2025-0023', entreprise: 'OTIS', objet: 'Ascenseurs' },
  { id: 155, numero: '2025-0024', entreprise: 'GROUPE SECHE', objet: 'Bacs à graisses' },
  { id: 156, numero: '2025-0145', entreprise: 'AC2P', objet: 'Aménagements' },
  { id: 157, numero: '2025-0146', entreprise: 'LEUILLET', objet: 'Façades rideaux' },
  { id: 158, numero: '2025-0147', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 159, numero: '2025-0148', entreprise: 'BSMG-LTDF', objet: 'CVC Plomberie' },
  { id: 160, numero: '2025-0177', entreprise: 'AC2P', objet: 'Gros œuvre - CEA' },
  { id: 161, numero: '2025-0178', entreprise: 'STPEE', objet: 'Electricité' },
  { id: 162, numero: '2025-0179', entreprise: 'MCFE', objet: 'CVC Plomberie' },
  { id: 163, numero: '2025-0282', entreprise: 'LEON GROSSE', objet: 'Gros œuvre - CEA' },
  { id: 164, numero: '2025-0283', entreprise: 'STPEE', objet: 'Electricité' },
  { id: 165, numero: '2025-0284', entreprise: 'BSMG-LTDF', objet: 'CVC Plomberie' },
  { id: 166, numero: '2025-0285', entreprise: 'OTIS', objet: 'Ascenseurs' },
  { id: 167, numero: '2025-0393', entreprise: 'RICHEZ_ASSOCIES (mandataires)', objet: 'Maîtrise d\'œuvre' },
  { id: 168, numero: '2025-0462', entreprise: 'BTP CONSULTANTS', objet: 'Bureau de contôle' },
  { id: 169, numero: '2025-0463', entreprise: 'ALPHA CONTRÔLE', objet: 'CSPS' },
  { id: 170, numero: '2025-0465', entreprise: 'ACORUS', objet: 'Agencement' },
  { id: 171, numero: '2025-0466', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 172, numero: '2025-0467', entreprise: 'MCFE', objet: 'Plomberie' },
  { id: 173, numero: '2025-0468', entreprise: 'CEGELEC', objet: 'SSI' },
  { id: 174, numero: '2025-0469', entreprise: 'DMF EXPERT', objet: 'Désenfumage' },
  { id: 175, numero: '2025-0562', entreprise: 'ENERBRAIN', objet: 'Gestion Energie' },
  { id: 176, numero: '2025-0581', entreprise: 'ETMB', objet: 'Agencement' },
  { id: 177, numero: '2025-0582', entreprise: 'SRM', objet: 'Serrurerie' },
  { id: 178, numero: '2025-0583', entreprise: 'CEGELEC', objet: 'Electricité' },
  { id: 179, numero: '2025-0584', entreprise: 'BSMG-LTDF', objet: 'Chauffage' },
  { id: 180, numero: '2025-0656', entreprise: 'BSMG-LTDF', objet: 'CVC' },
  { id: 181, numero: '2025-0657', entreprise: 'BSMG-LTDF', objet: 'Plomberie' },
  { id: 182, numero: '2025-0658', entreprise: 'ACCESS TP', objet: 'VRD' },
  { id: 183, numero: '2025-0659', entreprise: 'ACCESS TP', objet: 'VRD' },
  { id: 184, numero: '2025-0660', entreprise: 'ACCESS TP', objet: 'VRD' },
  { id: 185, numero: '2025-0661', entreprise: 'CCR', objet: 'Pierre de taille' },
  { id: 186, numero: '2025-0662', entreprise: 'CCR', objet: 'Pierre de taille' },
  { id: 187, numero: '2025-0759', entreprise: 'ROUGNON/AGS', objet: 'Groupes électrogènes' },
  { id: 188, numero: '2025-0769', entreprise: 'AC2P', objet: 'Aménagements int' },
  { id: 189, numero: '2025-0770', entreprise: 'TBES', objet: 'Electricité' },
  { id: 190, numero: '2025-0771', entreprise: 'BSMG-LTDF', objet: 'CVC Plomberie' },
  { id: 191, numero: '2025-0772', entreprise: 'ACCESS TP', objet: 'Aménagements Ext' },
  { id: 192, numero: '2025-0773', entreprise: 'SRM', objet: 'Metallerie - Serrurerie' },
  { id: 193, numero: '2025-0774', entreprise: 'OTIS', objet: 'Ascenseurs' },
  { id: 194, numero: '2025-0837', entreprise: 'ETMB', objet: 'Agencement' },
  { id: 195, numero: '2025-0838', entreprise: 'CEGELEC', objet: 'Electricité CFO CFA' },
  { id: 196, numero: '2025-0839', entreprise: 'BSMG-LTDF', objet: 'Chauffage/ventilation/plomberie/rafraichissement' },
  { id: 197, numero: '2025-0865', entreprise: 'ALMA ENTREPRISE', objet: 'GO étendu' },
  { id: 198, numero: '2025-0866', entreprise: 'ALMA ENTREPRISE', objet: 'CEA' },
  { id: 199, numero: '2025-0867', entreprise: 'COLAS France', objet: 'VRD' },
  { id: 200, numero: '2025-0868', entreprise: 'SCHNEIDER ET CIE', objet: 'CVC Plomberie' },
  { id: 201, numero: '2025-0870', entreprise: 'CEGELEC', objet: 'Electricité' },
];

export const SEED_OPES: Identifiant[] = [
  { id: 1, code: 'OPE 23-340', libelle: 'La Roseraie Phase 3 - Rénovation des ailes Monet' },
  { id: 2, code: 'OPE 23-340-01', libelle: 'Aménagement paysagé de l\'USLD La Roseraie et PDR' },
  { id: 3, code: 'OPE 23-367', libelle: 'Regroupement du pôle PDR à Neuilly-sur-Marne' },
  { id: 4, code: 'OPE 24-001-21', libelle: 'Rénovation du bâtiment admission pour transfert du somatique (49) et du SMPR (46)' },
  { id: 5, code: 'OPE 24-005-10', libelle: 'Aménagement d\'un foyer à R. de Gourmont (BISAC)' },
  { id: 6, code: 'OPE 24-018', libelle: 'Rénovation de l’hospitalisation RDC R+1 R+2 Piera Aulagnier' },
  { id: 7, code: 'OPE 24-107', libelle: 'Construction du bâtiment ALESIA' },
  { id: 8, code: 'OPE 24-489-04', libelle: 'HC R1 LASALLE (MARTINEZ)' },
  { id: 9, code: 'OPE 24-600', libelle: 'AMI Perray-Vaucluse' },
  { id: 10, code: 'OPE 24-691', libelle: 'Construction de l\'EHPAD' },
  { id: 11, code: 'OPE 25-008-01', libelle: 'Rénovation partielle à Hauteville R1 (HC LITINETSKAIA)' },
  { id: 12, code: 'OPE 25-535', libelle: 'CMP Compoint' },
  { id: 13, code: 'OPE 26-105', libelle: 'Installation d\'un 3e IRM à NSA' },
  { id: 14, code: 'OPE 26-221', libelle: 'Refection du site de Picot' },
  { id: 15, code: 'OPE 26-466-01', libelle: 'Avron R2 - Josephine BAKER' },
  { id: 16, code: 'OPE 26-489-05', libelle: 'HC R3 LASALLE (D\'ALBIS)' },
  { id: 17, code: 'OPE 26-551', libelle: 'Installation d\'un CMP et CATTP au 124 Bd Mac Donald' },
  { id: 18, code: 'OPE 26-686', libelle: 'Extension de la MAS du site de Perray' },
];

export const SEED_GERS: Identifiant[] = [
  { id: 1, code: 'GER 23-001', libelle: 'GHU' },
  { id: 2, code: 'GER 23-001-01', libelle: 'Remplacement et modernisation des ascenseurs du GHU' },
  { id: 3, code: 'GER 23-001-04', libelle: 'Remplacement des groupes froids du GHU : bât. 227 IPB et bât. 700 Henri Ey' },
  { id: 4, code: 'GER 23-001-05', libelle: 'Remplacement de système de régulation optimisée sur le GHU' },
  { id: 5, code: 'GER 23-001-06', libelle: 'Réfection du calorifuge dans les sous-stations, isolation des planchers et des combles du GHU' },
  { id: 6, code: 'GER 23-001-08', libelle: 'Installation et rénovation de système de récupération des eaux pluviales CHSA (phase 1)' },
  { id: 7, code: 'GER 24-001', libelle: 'GHU' },
  { id: 8, code: 'GER 24-001-03', libelle: 'Remplacement des groupes froids du GHU : bât. 35 self et bât. 489 Lasalle' },
  { id: 9, code: 'GER 24-001-04', libelle: 'Remplacement des réseaux hydraulique du site Sainte-Anne (chauffage, eau froide, défense incendie)' },
  { id: 10, code: 'GER 24-001-05', libelle: 'Remplacement des moteurs et variateurs de vitesse des circulateurs (chauffage, eau glacée, recyclage ECS)' },
  { id: 11, code: 'GER 24-001-06', libelle: 'Remplacement de l\'organigramme des clefs du GHU' },
  { id: 12, code: 'GER 24-001-07', libelle: 'Modernisation de la gestion technique des bâtiments (GTB) du GHU' },
  { id: 13, code: 'GER 23-002', libelle: 'Site Sainte-Anne' },
  { id: 14, code: 'GER 23-002-01', libelle: 'Rénovation de l\'éclairage extérieur du site Sainte Anne (phase 1)' },
  { id: 15, code: 'GER 23-002-02', libelle: 'Requalification de la sous-station thermique du bât. 67 pavillon de l\'horloge' },
  { id: 16, code: 'GER 24-002', libelle: 'Site Sainte-Anne' },
  { id: 17, code: 'GER 24-002-01', libelle: 'Rénovation de la galerie du Pavillon AC - Pavillon AL du site Sainte Anne' },
  { id: 18, code: 'GER 24-002-02', libelle: 'Renouvellement des compteurs d\'énergie sur le site Sainte-Anne' },
  { id: 19, code: 'GER 24-002-03', libelle: 'Renouvellement des onduleurs du site Sainte-Anne' },
  { id: 20, code: 'GER 25-002', libelle: 'Site Sainte-Anne' },
  { id: 21, code: 'GER 25-002-01', libelle: 'Remplacement des reports SSI du site Sainte-Anne vers le PC Sécurité incendie' },
  { id: 22, code: 'GER 25-002-03', libelle: 'Refection des enrobés de l\'entrée livraison de l\'hôpital et de la cours logistique' },
  { id: 23, code: 'GER 23-003', libelle: 'Site Perray-Vaucluse' },
  { id: 24, code: 'GER 23-003-01', libelle: 'Rénovation de la chaufferie Bourneville (EHPAD) sur le site de Perray-Vaucluse' },
  { id: 25, code: 'GER 25-018', libelle: 'Piera Aulagnier' },
  { id: 26, code: 'GER 25-018-01', libelle: 'Remplacement des menuiseries extérieures du bâtiment Piera Aulagnier' },
  { id: 27, code: 'GER 24-036', libelle: 'Rotonde' },
  { id: 28, code: 'GER 24-036-01', libelle: 'Travaux de ravallement du bâtiment Rotonde' },
  { id: 29, code: 'GER 23-039', libelle: 'UCP' },
  { id: 30, code: 'GER 23-039-01', libelle: 'Remplacement du SSI : bât. 39 UCP' },
  { id: 31, code: 'GER 25-039', libelle: 'UCP' },
  { id: 32, code: 'GER 25-039-01', libelle: 'Remplacement du TGBT de zone : bât. 39 UCP' },
  { id: 33, code: 'GER 24-041', libelle: 'SHU' },
  { id: 34, code: 'GER 24-041-01', libelle: 'Installation d\'un groupe froid pour les chambres d\'hospitalisation du bât. 41 SHU' },
  { id: 35, code: 'GER 24-041-02', libelle: 'Rénovation de l\'installation solaire thermique du bât. 41 SHU' },
  { id: 36, code: 'GER 24-057', libelle: 'DITMP' },
  { id: 37, code: 'GER 24-057-02', libelle: 'Ravalement, remplacement des menuiseries extérieures et restauration des couvertures du bât. 57-58 DITMP' },
  { id: 38, code: 'GER 24-100', libelle: 'CMME' },
  { id: 39, code: 'GER 24-100-01', libelle: 'Modernisation et mise à niveau de la gestion technique de l\'éclairage du bât. 100 CMME' },
  { id: 40, code: 'GER 24-227', libelle: 'Institut Paris Brune' },
  { id: 41, code: 'GER 24-227-01', libelle: 'Ravalement et restauration des couvertures du site IPB' },
  { id: 42, code: 'GER 24-369', libelle: 'PSP' },
  { id: 43, code: 'GER 24-369-01', libelle: 'Remplacement du SSI : bât. 369 PSP site NSM' },
  { id: 44, code: 'GER 23-408', libelle: 'Tour d\'Auvergne' },
  { id: 45, code: 'GER 23-408-01', libelle: 'Remplacement du SSI : bât. 408 Tour d\'Auvergne' },
  { id: 46, code: 'GER 23-466', libelle: 'Avron' },
  { id: 47, code: 'GER 23-466-01', libelle: 'Remplacement du système de chauffage existant gaz par CPCU' },
  { id: 48, code: 'GER 24-466', libelle: 'Avron' },
  { id: 49, code: 'GER 24-466-01', libelle: 'Remplacement du SSI : bât. 466 Avron' },
  { id: 50, code: 'GER 23-467', libelle: 'Hauteville' },
  { id: 51, code: 'GER 23-467-01', libelle: 'Remplacement du SSI : bât. 467 Hauteville' },
  { id: 52, code: 'GER 24-485', libelle: 'Bichat' },
  { id: 53, code: 'GER 24-485-01', libelle: 'Remplacement du SSI : bât. 485 Bichat' },
  { id: 54, code: 'GER 24-538', libelle: 'Marmottan' },
  { id: 55, code: 'GER 24-538-01', libelle: 'Ravalement et restauration des couvertures du site Marmottan' },
  { id: 56, code: 'GER 23-700', libelle: 'Henri Ey' },
  { id: 57, code: 'GER 23-700-01', libelle: 'Modification du TGBT et du TGS du bât. 700 Henri Ey' },
  { id: 58, code: 'GER 23-700-02', libelle: 'Remplacement d\'une CTA double flux desservant le R+6/7/8 du bât. 700 Henri Ey' },
  { id: 59, code: 'GER 24-700', libelle: 'Henri Ey' },
  { id: 60, code: 'GER 24-700-01', libelle: 'Amélioration de la performance énergétique et rénovation des façades du site Henri Ey' },
];

export const SEED_PTRS: Identifiant[] = [
  { id: 1, code: 'PTR 26-001', libelle: 'Budget de fonctionnement site Sainte-Anne' },
  { id: 2, code: 'PTR 26-002', libelle: 'Budget de fonctionnement site Perray-Vaucluse' },
  { id: 3, code: 'PTR 26-002-01', libelle: 'Budget préalable aux cessions' },
  { id: 4, code: 'PTR 26-003', libelle: 'Budget de fonctionnement site Neuilly sur Marne' },
  { id: 5, code: 'PTR 26-004', libelle: 'Budget de fonctionnement sites ambulatoires Sud' },
  { id: 6, code: 'PTR 26-005', libelle: 'Budget de fonctionnement sites ambulatoires Nord' },
  { id: 7, code: 'PTR 26-227', libelle: 'Budget de fonctionnement site IPB' },
  { id: 8, code: 'PTR 26-466', libelle: 'Budget de fonctionnement site Avron' },
  { id: 9, code: 'PTR 26-467', libelle: 'Budget de fonctionnement site Hauteville' },
  { id: 10, code: 'PTR 26-467-01', libelle: 'Travaux SDB CAP' },
  { id: 11, code: 'PTR 26-485', libelle: 'Budget de fonctionnement site Bichat' },
  { id: 12, code: 'PTR 26-489', libelle: 'Budget de fonctionnement site Lasalle' },
  { id: 13, code: 'PTR 26-538', libelle: 'Budget de fonctionnement site Marmottan' },
  { id: 14, code: 'PTR 26-700', libelle: 'Budget de fonctionnement site Henri EY' },
];

export const SEED_POLES: Pole[] = [
  { id: 1, code: '5/6/7e', libelle: '5/6/7e' },
  { id: 2, code: 'Coordination 8/9/10e', libelle: '8/9/10e — Coordination 8/9/10e' },
  { id: 3, code: 'G05-06', libelle: '8/9/10e — G05-06' },
  { id: 4, code: 'G07', libelle: '8/9/10e — G07' },
  { id: 5, code: 'I03', libelle: '8/9/10e — I03' },
  { id: 6, code: '14e', libelle: '14e' },
  { id: 7, code: '15e', libelle: '15e' },
  { id: 8, code: '16e', libelle: '16e' },
  { id: 9, code: 'somatique-USLD', libelle: '17e — somatique-USLD' },
  { id: 10, code: 'Coordination 17e', libelle: '17e — Coordination 17e' },
  { id: 11, code: 'G19', libelle: '17e — G19' },
  { id: 12, code: 'G20-21', libelle: '17e — G20-21' },
  { id: 13, code: 'I09', libelle: '17e — I09' },
  { id: 14, code: 'Coordination 18e', libelle: '18e — Coordination 18e' },
  { id: 15, code: 'G22', libelle: '18e — G22' },
  { id: 16, code: 'G23', libelle: '18e — G23' },
  { id: 17, code: 'G24', libelle: '18e — G24' },
  { id: 18, code: 'Coordination 19e', libelle: '19e — Coordination 19e' },
  { id: 19, code: 'G25', libelle: '19e — G25' },
  { id: 20, code: 'G26', libelle: '19e — G26' },
  { id: 21, code: 'I11', libelle: '19e — I11' },
  { id: 22, code: 'Coordination 20e', libelle: '20e — Coordination 20e' },
  { id: 23, code: 'G27', libelle: '20e — G27' },
  { id: 24, code: 'G28', libelle: '20e — G28' },
  { id: 25, code: 'G29', libelle: '20e — G29' },
  { id: 26, code: 'CMME', libelle: 'CMME' },
  { id: 27, code: 'CPOA-SMPR-PSYLINE', libelle: 'CPOA-SMPR-PSYLINE' },
  { id: 28, code: 'Direction', libelle: 'Direction' },
  { id: 29, code: 'Médico-social PV', libelle: 'Médico-social PV' },
  { id: 30, code: 'Médico-technique', libelle: 'Médico-technique' },
  { id: 31, code: 'Moreau de Tours', libelle: 'Moreau de Tours' },
  { id: 32, code: 'Multi Pôles', libelle: 'Multi Pôles' },
  { id: 33, code: 'Neuro-Sainte-Anne', libelle: 'Neuro-Sainte-Anne' },
  { id: 34, code: 'PDR', libelle: 'PDR' },
  { id: 35, code: 'PEPIT', libelle: 'PEPIT' },
  { id: 36, code: 'Précarité', libelle: 'Précarité' },
  { id: 37, code: 'Somatique-USLD', libelle: 'Somatique-USLD' },
  { id: 38, code: 'Toxicomanie', libelle: 'Toxicomanie' },
];

export const SIMULATED_EXTRACTION = {
  numDevis: 'PR2605-30393',
  totalHT: '1 283,48',
  tva: '20' as const,
  dateDebut: '2026-05-27',
  dateFin: '2026-06-27',
  natureTravaux: 'Dépannage SERSI-LVCOM (Site Hauteville)',
  type: 'cl6' as const,
  batimentNumero: '467',
  entrepriseNom: 'SERSI - LVCOM',
};

export const BUDGET_OPTIONS = ['H', 'Annexe B', 'Annexe C', 'Annexe E', 'Annexe P'];
